import myHeader from "./components/myHeader.js";
import banner from "./components/banner.js";
import myPost from "./components/myPost.js";
import myAside from "./components/myAside.js";
import myContent from "./components/myContent.js";
import myContentwTable from "./components/myContentwTable.js";
import myFooter from "./components/myFooter.js";
myHeader.show();
banner.showImage();
banner.show();
myPost.show();
myAside.show();
myContent.show();
myContentwTable.show();
myContentwTable.show2();
myContentwTable.show3();
myContentwTable.show4();
myFooter.show();